# -*- coding: utf-8 -*-
"""flipkart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKSuMKI1XP_GVcUKCUY0A344dIdmVdsr
"""

import requests
import re
from bs4 import BeautifulSoup
import csv

################################### FLIPKART #######################
page = requests.get('https://www.flipkart.com/q/ps4-games').text
soup = BeautifulSoup(page, 'lxml')
#print(soup.prettify())

#Creamos y abrimos el archivo csv1
csv_file = open('flipkart.csv','w')
csv_writer = csv.writer(csv_file)
csv_writer.writerow(['Titulo','Publicador','Desarrollador','Genero','Edad','Link1','Link2'])

#Creamos todas las paginas de la buygames
lastpage = int(soup.find('div', class_='_2zg3yZ').span.text.split(' ')[3])
pages=[]
for i in range(1,lastpage+1):
  page= 'https://www.flipkart.com/q/ps4-games?page='+str(i)
  pages.append(page)

#Buscamos los datos en todas las paginas de la BuyGames
for page in pages:
  pagex = requests.get(page).text
  soupx = BeautifulSoup(pagex, 'lxml')
  gamesx = soupx.find_all('a', class_='_2cLu-l')
  for game in gamesx:
    link = 'https://www.flipkart.com'+game['href']
    data = requests.get(link).text
    soup = BeautifulSoup(data, 'lxml')
    if (soup.find('td',class_='_3-wDH3 col col-3-12', text=('Title Name'))):
      title = soup.find('td',class_='_3-wDH3 col col-3-12', text=('Title Name')).findNext('li', class_='_3YhLQA').text
    else:
      continue
    if (soup.find('table', class_='_3ENrHu').findNext(text=('Publisher'))):
      publisher = soup.find('table', class_='_3ENrHu').findNext(text=('Publisher')).findNext('li').text.strip()
    else:
      publisher = 'None'
    if (soup.find('table', class_='_3ENrHu').findNext(text=('Developer'))):
      developer = soup.find('table', class_='_3ENrHu').findNext(text=('Developer')).findNext('li').text.strip()
    else:
      developer = 'None'
    if (soup.find('table', class_='_3ENrHu').findNext(text=('Genre'))):
      genre = soup.find('table', class_='_3ENrHu').findNext(text=('Genre')).findNext('li').text.strip()
    else:
      genre = 'None'
    if (soup.find('table', class_='_3ENrHu').findNext(text=('PEGI'))):
      age = soup.find('table', class_='_3ENrHu').findNext(text=('PEGI')).findNext('li').text.strip()
    else:
      age = 'None'
    csv_writer.writerow([title,publisher,developer,genre,age,link,'None'])

csv_file.close()