# -*- coding: utf-8 -*-
"""juegos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cJLivhgvU9kbwLZRtGfTzaJ2RXCIPN5M
"""

!pip install fuzzywuzzy

import pandas as pd
from fuzzywuzzy import fuzz


x = pd.read_csv('flipkart.csv')
y = pd.read_csv('mightyape.csv')
z = pd.DataFrame(columns=['Titulo','Publicador','Desarrollador','Genero','Edad','Link1','Link2','Comments'])
z = z.append(x.loc[0],ignore_index=True)
for i in range(len(x)):
  c = 0
  a = x.at[i,'Titulo']
  for m in range(len(z)):
    b = z.at[m,'Titulo']
    if fuzz.ratio(a.lower(),b.lower())>80:
      c = c+1
  if c==0:
    z = z.append(x.loc[i],ignore_index=True)

for j in range(len(y)):
  c = 0
  a = y.at[j,'Titulo']
  for m in range(len(z)):
    b = z.at[m,'Titulo']
    if fuzz.ratio(a.lower(),b.lower())>80:
      c = c+1
      if z.at[m,'Publicador']=='None':
        z.at[m,'Publicador']=y.at[j,'Publicador']
      if z.at[m,'Desarrollador']=='None':
        z.at[m,'Desarrollador']=y.at[j,'Desarrollador']
      if z.at[m,'Genero']=='None':
        z.at[m,'Genero']=y.at[j,'Genero']
      if z.at[m,'Edad']=='None':
        z.at[m,'Edad']=y.at[j,'Edad']
      if z.at[m,'Link2']=='None':
        z.at[m,'Link2']=y.at[j,'Link2']
  if c==0:
    z = z.append(y.loc[j],ignore_index=True)
z.to_csv('juegos.csv')