# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKSuMKI1XP_GVcUKCUY0A344dIdmVdsr
"""

import requests
import re
from bs4 import BeautifulSoup
import csv

################################### MIGHTYAPE #######################
#Creamos y abrimos el archivo csv
csv_file = open('mightyape.csv','w')
csv_writer = csv.writer(csv_file)
csv_writer.writerow(['Titulo','Publicador','Desarrollador','Genero','Edad','Link1','Link2'])
#Agregamos todos los generos de la página a una lista
genres = ['action','adventure-rpg','sports','driving-games','simulation-strategy','playstationvr','fighting','party-games']
#Definimos la funcion que recolecta información
def mightyape(genre):
  page = requests.get('https://www.mightyape.co.nz/games/ps4/ps4-games/'+genre+'/all?page=1').text
  soup = BeautifulSoup(page, 'lxml')
  if (soup.find('span', class_='icon-more-right')):
    lastpage = int(soup.find('span', class_='icon-more-right').findPrevious('li').findPrevious('li').text)
  else:
    lastpage = 1
  pages = []
  for i in range(1,lastpage+1):
    pages.append('https://www.mightyape.co.nz/games/ps4/ps4-games/'+genre+'/all?page='+str(i))
  #Buscamos los datos en todas las paginas de la Migthyape
  for page in pages:
    pagex = requests.get(page).text
    soupx = BeautifulSoup(pagex, 'lxml')
    gamelistx = soupx.find('div', class_='product-list gallery-view')
    gamesx = gamelistx.find_all('div', class_='product')
    #Añadimos toda la info de Mightyape al archivo
    for game in gamesx:
      link = 'https://www.mightyape.co.nz'+game.find('a')['href']
      data = requests.get(link).text
      soup = BeautifulSoup(data, 'lxml')
      title = soup.find('div', class_='product-summary-header').h1.text
      if (soup.find('div' , class_='product-details').find(text=re.compile('Publisher'))):
        publisher = soup.find('div' , class_='product-details').find(text=re.compile('Publisher')).findNext('a').text.strip()
      else:
        publisher = 'None'
      if (soup.find('div' , class_='product-details').find(text=re.compile('Developer'))):
        developer = soup.find('div' , class_='product-details').find(text=re.compile('Developer')).findNext('a').text.strip()
      else:
        developer = 'None'
      if (soup.find('p', class_='description')):
        age = soup.find('p', class_='description').text.strip()
      else:
        age = 'None'
      csv_writer.writerow([title,publisher,developer,genre,age,'None',link])
#Ejecutamos la función para cada genero
for x in genres:
  mightyape(x)
csv_file.close()